# Generated by Django 4.0.1 on 2022-02-01 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnavailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_user', to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(choices=[('Vocals', 'vocals'), ('Guitar', 'guitar'), ('Bass Guitar', 'bass guitar'), ('Keyboard', 'keyboard'), ('Piano', 'piano'), ('Drums', 'drums'), ('Percussion', 'percussion'), ('Trumpet', 'trumpet'), ('Tenor Trombone', 'tenor trombone'), ('Bass Trombone', 'bass_trombone'), ('Sousaphone', 'sousaphone'), ('Alto Saxphone', 'alto saxophone'), ('Tenor Saxophone', 'tenor saxophone'), ('Baritone Saxophone', 'baritone saxophone'), ('Flute', 'flute'), ('Clarinet', 'clarinet'), ('Accordion', 'accordion'), ('Violin', 'violin'), ('Viola', 'viola'), ('Cello', 'cello'), ('Double Bass', 'double bass'), ('Harmonica', 'harmonica'), ('Vibraphone', 'vibraphone')], default='', max_length=50)),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to='profiles.userprofile')),
            ],
        ),
    ]
