# Generated by Django 4.0.2 on 2022-02-11 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(blank=True, choices=[('Pop', 'pop'), ('Rock', 'rock'), ('Jazz', 'jazz'), ('Classical', 'classical'), ('Funk', 'funk'), ('Soul', 'soul'), ('RnB', 'rnb'), ('Punk', 'punk'), ('Latin', 'latin'), ('Bossa Nova', 'bossa_nova'), ('Hip Hop', 'hip_hop'), ('Metal', 'metal'), ('Prog Rock', 'prog_rock'), ('Experimental', 'experimental'), ('Ambient', 'ambient'), ('Club Music', 'club_music'), ('House', 'house')], max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(blank=True, choices=[('Vocals', 'vocals'), ('Guitar', 'guitar'), ('Bass Guitar', 'bass guitar'), ('Keyboard', 'keyboard'), ('Piano', 'piano'), ('Drums', 'drums'), ('Percussion', 'percussion'), ('Trumpet', 'trumpet'), ('Tenor Trombone', 'tenor trombone'), ('Bass Trombone', 'bass_trombone'), ('Sousaphone', 'sousaphone'), ('Alto Saxphone', 'alto saxophone'), ('Tenor Saxophone', 'tenor saxophone'), ('Baritone Saxophone', 'baritone saxophone'), ('Flute', 'flute'), ('Clarinet', 'clarinet'), ('Accordion', 'accordion'), ('Violin', 'violin'), ('Viola', 'viola'), ('Cello', 'cello'), ('Double Bass', 'double bass'), ('Harmonica', 'harmonica'), ('Vibraphone', 'vibraphone')], max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('user_info', models.TextField(blank=True, null=True)),
                ('subscription_chosen', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('genres', models.ManyToManyField(to='profiles.Genre')),
                ('instruments_played', models.ManyToManyField(to='profiles.Instrument')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnavailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_user', to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=300)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='profiles.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio')),
                ('title', models.CharField(max_length=100)),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_tracks', to='profiles.userprofile')),
            ],
        ),
    ]
