# Generated by Django 4.0.1 on 2022-02-01 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio')),
                ('title', models.CharField(max_length=100)),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_tracks', to='profiles.userprofile')),
            ],
        ),
    ]
