# Generated by Django 4.0.2 on 2022-02-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unavailabledate',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
