# Generated by Django 4.0.1 on 2022-02-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_audiofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
