# Generated by Django 4.0.2 on 2022-02-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_audiofile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
