# Generated by Django 4.0.2 on 2022-02-23 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_invitation_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='invitation_count',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
