# Generated by Django 4.0.2 on 2022-03-03 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_sheetmusic'),
        ('profiles', '0008_userprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='related_booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_resources', to='bookings.booking'),
        ),
    ]
