# Generated by Django 4.0.2 on 2022-03-03 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_audiofile_related_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='related_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_tracks', to='profiles.userprofile'),
        ),
    ]
