# Generated by Django 4.0.2 on 2022-03-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_sheetmusic'),
        ('profiles', '0010_alter_audiofile_related_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='related_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_resources', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_tracks', to='profiles.userprofile'),
        ),
    ]
