# Generated by Django 4.0.2 on 2022-03-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_audiofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
    ]
