# Generated by Django 4.0.2 on 2022-03-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_audiofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(blank=True, choices=[('Pop', 'pop'), ('Rock', 'rock'), ('Jazz', 'jazz'), ('Classical', 'classical'), ('Funk', 'funk'), ('Soul', 'soul'), ('RnB', 'rnb'), ('Punk', 'punk'), ('Latin', 'latin'), ('Bossa Nova', 'bossa_nova'), ('Hip Hop', 'hip_hop'), ('Metal', 'metal'), ('Prog Rock', 'prog_rock'), ('Experimental', 'experimental'), ('Ambient', 'ambient'), ('Club Music', 'club_music'), ('House', 'house')], default='All', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_name',
            field=models.CharField(blank=True, choices=[('Vocals', 'vocals'), ('Guitar', 'guitar'), ('Bass Guitar', 'bass guitar'), ('Keyboard', 'keyboard'), ('Piano', 'piano'), ('Drums', 'drums'), ('Percussion', 'percussion'), ('Trumpet', 'trumpet'), ('Tenor Trombone', 'tenor trombone'), ('Bass Trombone', 'bass_trombone'), ('Sousaphone', 'sousaphone'), ('Alto Saxphone', 'alto saxophone'), ('Tenor Saxophone', 'tenor saxophone'), ('Baritone Saxophone', 'baritone saxophone'), ('Flute', 'flute'), ('Clarinet', 'clarinet'), ('Accordion', 'accordion'), ('Violin', 'violin'), ('Viola', 'viola'), ('Cello', 'cello'), ('Double Bass', 'double bass'), ('Harmonica', 'harmonica'), ('Vibraphone', 'vibraphone')], default='All', max_length=50, null=True, unique=True),
        ),
    ]
