# Generated by Django 4.0.2 on 2022-03-11 23:00

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0014_alter_genre_genre_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150)),
                ('artist_name', models.CharField(blank=True, max_length=100, null=True)),
                ('job_description', models.TextField(max_length=500)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=100, null=True)),
                ('street_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('event_city', models.CharField(max_length=100)),
                ('event_country', django_countries.fields.CountryField(max_length=2)),
                ('event_datetime', models.DateTimeField()),
                ('travel_provided', models.BooleanField(default=False, null=True)),
                ('travel_info', models.TextField(blank=True, null=True)),
                ('backline_provided', models.BooleanField(default=False, null=True)),
                ('backline_info', models.TextField(blank=True, null=True)),
                ('interest_count', models.IntegerField(blank=True, default=0, null=True)),
                ('is_taken', models.BooleanField(default=False)),
                ('interested_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='profiles.userprofile')),
                ('job_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='profiles.userprofile')),
            ],
        ),
    ]
