# Generated by Django 4.0.2 on 2022-03-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='backline_info',
        ),
        migrations.RemoveField(
            model_name='job',
            name='backline_provided',
        ),
        migrations.RemoveField(
            model_name='job',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='job',
            name='street_address1',
        ),
        migrations.RemoveField(
            model_name='job',
            name='street_address2',
        ),
        migrations.RemoveField(
            model_name='job',
            name='travel_info',
        ),
        migrations.RemoveField(
            model_name='job',
            name='travel_provided',
        ),
        migrations.RemoveField(
            model_name='job',
            name='venue_name',
        ),
        migrations.AddField(
            model_name='job',
            name='job_title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
