# Generated by Django 4.0.2 on 2022-03-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_genre_genre_name_and_more'),
        ('jobs', '0006_remove_job_interested_member_job_interested_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='interested_member',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.UserProfile'),
        ),
    ]
