# Generated by Django 4.0.2 on 2022-03-14 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_genre_genre_name_and_more'),
        ('jobs', '0007_alter_job_interested_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='confirmed_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_jobs', to='profiles.userprofile'),
        ),
    ]
