# Generated by Django 4.0.2 on 2022-03-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_confirmed_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='instrument_required',
        ),
    ]
