# Generated by Django 4.0.2 on 2022-03-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_userprofile_average_rating'),
        ('jobs', '0010_job_job_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='interested_member',
            field=models.ManyToManyField(blank=True, to='profiles.UserProfile'),
        ),
    ]
