# Generated by Django 4.0.2 on 2022-02-26 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0004_invitation_fee'),
        ('profiles', '0008_userprofile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_message', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=400)),
                ('invitation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_messages', to='bookings.invitation')),
                ('message_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='profiles.userprofile')),
                ('message_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='profiles.userprofile')),
            ],
        ),
    ]
