# Generated by Django 4.0.2 on 2022-03-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='declined_invitation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
