# Generated by Django 4.0.2 on 2022-03-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_job_instrument_required'),
        ('social', '0006_notification_declined_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='related_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_messages', to='jobs.job'),
        ),
    ]
