# Generated by Django 4.0.2 on 2022-03-19 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_message_related_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(7)]),
        ),
    ]
