# Generated by Django 4.0.2 on 2022-02-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
