# Generated by Django 4.0.2 on 2022-02-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_invitation_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
