# Generated by Django 4.0.2 on 2022-03-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_country_booking_postcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='venue_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
