# Generated by Django 4.0.2 on 2022-03-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_venue_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='country',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='town_or_city',
        ),
    ]
