# Generated by Django 4.0.2 on 2022-03-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_remove_booking_country_remove_booking_town_or_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_details_sent',
            field=models.BooleanField(default=False),
        ),
    ]
