# Generated by Django 4.0.2 on 2022-03-10 14:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_genre_genre_name_and_more'),
        ('bookings', '0012_booking_booking_details_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.TextField(max_length=800)),
                ('review_created', models.DateTimeField(editable=False)),
                ('review_modified', models.DateTimeField()),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('related_booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking')),
                ('review_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='profiles.userprofile')),
                ('review_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_reviews', to='profiles.userprofile')),
            ],
        ),
    ]
