# Generated by Django 4.0.2 on 2022-03-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
