# Generated by Django 4.0.2 on 2022-03-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_genre_genre_name_and_more'),
        ('bookings', '0014_alter_review_review_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='related_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_reviews', to='profiles.userprofile'),
        ),
    ]
