# Generated by Django 4.0.2 on 2022-03-14 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_interested_member'),
        ('bookings', '0015_alter_review_related_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='related_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_job', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='related_invitation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_booking', to='bookings.invitation'),
        ),
    ]
