# Generated by Django 4.0.2 on 2022-03-19 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_job_instrument_required'),
        ('bookings', '0016_booking_related_job_alter_booking_related_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='related_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_booking', to='jobs.job'),
        ),
    ]
