# Generated by Django 4.0.2 on 2022-03-31 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_userprofile_average_rating'),
        ('bookings', '0019_delete_sheetmusic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invite_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invite_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to='profiles.userprofile'),
        ),
    ]
